baseURL = "http://www.farm.style"
title = "farm.style | farm.red studios design "

# Directories
publishDir = "../public"

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true
pygmentsStyle = "emacs"
pygmentsUseClasses=true

[params.info]
description = "farm.red studios design system"
title404 = "Not anywhere here"

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[markup]
  defaultMarkdownHandler = "blackfriday"
  [markup.blackFriday]
    hrefTargetBlank = true